"""
Configuration mapping of common third-party application names to their
executable filenames. Used by the app launcher and closer to resolve
voice commands such as 'open chrome' or 'close spotify'.
"""

from typing import Dict

# Regular (third-party) applications dictionary
APPS: Dict[str, str] = {
    "chrome": "chrome.exe",
    "edge": "msedge.exe",
    "firefox": "firefox.exe",
    "opera": "opera.exe",
    "code": "code.exe",
    "visual studio": "devenv.exe",
    "pycharm": "pycharm64.exe",
    "intellij": "idea64.exe",
    "android studio": "studio64.exe",
    "eclipse": "eclipse.exe",
    "netbeans": "netbeans64.exe",
    "word": "winword.exe",
    "excel": "excel.exe",
    "powerpoint": "powerpnt.exe",
    "outlook": "outlook.exe",
    "onenote": "onenote.exe",
    "access": "msaccess.exe",
    "publisher": "mspub.exe",
    "visio": "visio.exe",
    "project": "winproj.exe",
    "teams": "teams.exe",
    "skype": "skype.exe",
    "zoom": "zoom.exe",
    "discord": "discord.exe",
    "slack": "slack.exe",
    "whatsapp": "whatsapp.exe",
    "telegram": "telegram.exe",
    "vscode": "code.exe",
    "notepad": "notepad++.exe",
    "sublime": "sublime_text.exe",
    "atom": "atom.exe",
    "photoshop": "photoshop.exe",
    "illustrator": "illustrator.exe",
    "premiere": "premiere.exe",
    "after effects": "afterfx.exe",
    "lightroom": "lightroom.exe",
    "acrobat": "acrobat.exe",
    "reader": "acrord32.exe",
    "winrar": "winrar.exe",
    "7zip": "7zfm.exe",
    "winzip": "winzip64.exe",
    "spotify": "spotify.exe",
    "vlc": "vlc.exe",
    "media player": "wmplayer.exe",
    "quicktime": "quicktimeplayer.exe",
    "itunes": "itunes.exe",
    "steam": "steam.exe",
    "epic games": "epicgameslauncher.exe",
    "origin": "origin.exe",
    "battle.net": "battle.net.exe",
    "utorrent": "utorrent.exe",
    "bittorrent": "bittorrent.exe",
    "qbittorrent": "qbittorrent.exe",
    "teamviewer": "teamviewer.exe",
    "anydesk": "anydesk.exe",
    "ccleaner": "ccleaner64.exe",
    "malwarebytes": "mbam.exe",
    "avast": "avastui.exe",
    "avg": "avgui.exe",
    "norton": "norton.exe",
    "kaspersky": "avp.exe",
    "python": "python.exe",
    "java": "javaw.exe",
    "node": "node.exe",
    "git": "git-bash.exe",
    "docker": "docker.exe",
    "postman": "postman.exe",
    "mysql": "mysql.exe",
    "workbench": "mysqlworkbench.exe",
    "mongodb": "mongodb.exe",
    "redis": "redis-server.exe",
    "virtualbox": "virtualbox.exe",
    "vmware": "vmware.exe",
    "hyper-v": "vmconnect.exe",
    "blender": "blender.exe",
    "maya": "maya.exe",
    "3ds max": "3dsmax.exe",
    "cinema 4d": "cinema4d.exe",
    "unity": "unity.exe",
    "unreal": "unrealengine.exe",
    "godot": "godot.exe",
    "obs": "obs64.exe",
    "streamlabs": "streamlabs.exe",
    "xsplit": "xsplit.exe",
    "camtasia": "camtasia.exe",
    "audacity": "audacity.exe",
    "gimp": "gimp-2.10.exe",
    "inkscape": "inkscape.exe",
    "krita": "krita.exe",
    "lightshot": "lightshot.exe",
    "sharex": "sharex.exe",
    "greenshot": "greenshot.exe",
    "evernote": "evernote.exe",
    "notion": "notion.exe",
    "todoist": "todoist.exe",
    "trello": "trello.exe",
    "asana": "asana.exe",
    "clickup": "clickup.exe",
}
