"""
Configuration mapping of common website names to their URLs. Used by the
app launcher to resolve voice commands such as 'open youtube' into a
browser navigation action.
"""

from typing import Dict

# Websites dictionary
SITES: Dict[str, str] = {
    "google": "https://www.google.com",
    "youtube": "https://www.youtube.com",
    "facebook": "https://www.facebook.com",
    "instagram": "https://www.instagram.com",
    "twitter": "https://www.twitter.com",
    "linkedin": "https://www.linkedin.com",
    "github": "https://www.github.com",
    "stackoverflow": "https://stackoverflow.com",
    "reddit": "https://www.reddit.com",
    "wikipedia": "https://www.wikipedia.org",
    "amazon": "https://www.amazon.com",
    "netflix": "https://www.netflix.com",
    "spotify": "https://www.spotify.com",
    "gmail": "https://mail.google.com",
    "outlook": "https://outlook.live.com",
    "drive": "https://drive.google.com",
    "dropbox": "https://www.dropbox.com",
    "whatsapp": "https://web.whatsapp.com",
    "telegram": "https://web.telegram.org",
    "discord": "https://discord.com",
    "twitch": "https://www.twitch.tv",
    "microsoft": "https://www.microsoft.com",
    "apple": "https://www.apple.com",
    "ubuntu": "https://ubuntu.com",
    "wordpress": "https://wordpress.com",
    "medium": "https://medium.com",
    "quora": "https://www.quora.com",
    "pinterest": "https://www.pinterest.com",
    "tumblr": "https://www.tumblr.com",
    "flickr": "https://www.flickr.com",
    "imgur": "https://imgur.com",
    "unsplash": "https://unsplash.com",
    "deviantart": "https://www.deviantart.com",
    "behance": "https://www.behance.net",
    "dribbble": "https://dribbble.com",
    "figma": "https://www.figma.com",
    "canva": "https://www.canva.com",
    "notion": "https://www.notion.so",
    "trello": "https://trello.com",
    "asana": "https://asana.com",
    "slack": "https://slack.com",
    "zoom": "https://zoom.us",
    "teams": "https://teams.microsoft.com",
    "skype": "https://web.skype.com",
    "signal": "https://signal.org",
    "paypal": "https://www.paypal.com",
    "stripe": "https://stripe.com",
    "coinbase": "https://www.coinbase.com",
    "binance": "https://www.binance.com",
    "kraken": "https://www.kraken.com",
    "booking": "https://www.booking.com",
    "airbnb": "https://www.airbnb.com",
    "tripadvisor": "https://www.tripadvisor.com",
    "expedia": "https://www.expedia.com",
    "kayak": "https://www.kayak.com",
    "uber": "https://www.uber.com",
    "lyft": "https://www.lyft.com",
    "doordash": "https://www.doordash.com",
    "ubereats": "https://www.ubereats.com",
    "grubhub": "https://www.grubhub.com",
    "yelp": "https://www.yelp.com",
    "zillow": "https://www.zillow.com",
    "realtor": "https://www.realtor.com",
    "indeed": "https://www.indeed.com",
    "glassdoor": "https://www.glassdoor.com",
    "monster": "https://www.monster.com",
    "craigslist": "https://craigslist.org",
    "ebay": "https://www.ebay.com",
    "etsy": "https://www.etsy.com",
    "walmart": "https://www.walmart.com",
    "target": "https://www.target.com",
    "bestbuy": "https://www.bestbuy.com",
    "homedepot": "https://www.homedepot.com",
    "lowes": "https://www.lowes.com",
    "ikea": "https://www.ikea.com",
    "wayfair": "https://www.wayfair.com",
    "overstock": "https://www.overstock.com",
}
