"""
Configuration mapping of Windows system applications/utilities to their
launch commands. Used by the app launcher to resolve voice commands such
as 'open control panel' into the correct shell command.
"""

from typing import Dict

# Windows system apps dictionary
SYSTEM_APPS: Dict[str, str] = {
    "control panel": "control",
    "task manager": "taskmgr",
    "file explorer": "explorer",
    "command prompt": "cmd",
    "powershell": "powershell",
    "calculator": "calc",
    "notepad": "notepad",
    "paint": "mspaint",
    "wordpad": "write",
    "character map": "charmap",
    "device manager": "devmgmt.msc",
    "disk management": "diskmgmt.msc",
    "services": "services.msc",
    "event viewer": "eventvwr",
    "system configuration": "msconfig",
    "registry editor": "regedit",
    "computer management": "compmgmt.msc",
    "windows features": "optionalfeatures",
    "programs and features": "appwiz.cpl",
    "network connections": "ncpa.cpl",
    "power options": "powercfg.cpl",
    "sound settings": "mmsys.cpl",
    "display settings": "desk.cpl",
    "mouse settings": "main.cpl",
    "keyboard settings": "control keyboard",
    "date and time": "timedate.cpl",
    "region settings": "intl.cpl",
    "user accounts": "netplwiz",
    "windows security": "windowsdefender:",
    "printer settings": "control printers",
    "bluetooth settings": "fsquirt",
    "windows update": "ms-settings:windowsupdate",
    "settings": "ms-settings:",
    "run dialog": "winver",
    "system information": "msinfo32",
    "resource monitor": "resmon",
    "performance monitor": "perfmon",
    "clipboard": "win+v",
    "magnifier": "magnify",
    "narrator": "narrator",
    "on-screen keyboard": "osk",
    "windows media player": "wmplayer",
    "sound recorder": "soundrecorder",
    "sticky notes": "stikynot",
    "snipping tool": "snippingtool",
    "xbox game bar": "gamebar",
    "camera": "microsoft.windows.camera:",
    "photos": "ms-photos:",
    "calendar": "outlookcal:",
    "mail": "outlookmail:",
    "store": "ms-windows-store:",
    "weather": "msnweather:",
    "news": "msnnews:",
    "sports": "msnsports:",
    "money": "msnmoney:",
    "travel": "msntravel:",
}
